import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
	discordComponentsSidebar: [{ type: 'autogenerated', dirName: '.' }]
};

export default sidebars;
