name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Building:
    name: Build Templates
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - angular
          - astro
          - htmx-vite-ts
          - nextjs-app-directory-ts
          - nextjs-ts
          - no-framework-vite
          - nuxt3-ts
          - preact-vite-ts
          - qwik-vite-ts
          - react-docusaurus-ts
          - react-vite-ts
          - solid-vite-ts
          - svelte-vite-ts
          - sveltekit-ts
          - vue-vite-ts
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5
      - name: Use Node.js v20
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: yarn
          registry-url: https://registry.yarnpkg.com/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build template ${{ matrix.path }}
        run: yarn build
        working-directory: templates/${{ matrix.path }}
